apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zyyl91wci-python 
  janus-idp.io/tekton: zyyl91wci-python
  backstage.io/kubernetes-id: zyyl91wci-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zyyl91wci-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml